### PR TITLE
Potential cross-platform design pattern

### PR DESCRIPTION
**Pull request by pmusgrave**
This is just a proposal, so definitely open to other ideas of how to structure things. Opening this pull request mainly for discussion of overall strategy. For cross platform support, I was thinking we could use [platform specific macros](https://sourceforge.net/p/predef/wiki/OperatingSystems/), and include different header files, each of which would have the same interface but different implementation for the target platform. So, we add the following:

```
#ifdef __APPLE__
#include "something_mac.h"
#elif __linux__
#include "something_linux.h"
#elif _WIN32
#include "something_win32.h"
#endif
```

and then each of those three files implements an interface for whatever API we would need. I used this for window creation, but this pattern could be followed whenever platform specific code needs to be handled.

The commits in this pull request introduce this pattern for window creation:
- `IWindow` - a pure virtual class to define a window API (open to different naming conventions for interfaces, just went with IWindow for now)
- `MainWindow` a general class that abstracts the platform specific versions
- `MainWindow_X11` - an implementation of the linux version of this virtual class. I also added a `MainWindow` instantiation to `main.cc`, which works on my (linux) system.
- the basic #ifdef structure of how this would be used. I ended up using these ifdefs in the general class's constructor, and using these to set a member variable of type IWindow

So, all external code would create an instance of the general class, MainWindow. Calling one of the general class's methods would internally execute the platform specific version. This means the majority of the codebase would not need any ifdefs, which keeps things cleaner, and would make things more portable because the application code does not need to know specifics of which platform is being targeted.

If this method seems good, we would just need to put the Mac window creation code in a MainWindow_Mac class, and add this line to the MainWindow class:
```
#ifdef __APPLE__
  this->platform_window_ = new MainWindow_Mac();
```

### CODE REVIEW

**Comment by musgravejw** [comment]
@domfarolino This was ok to merge right?  (after rebase)

**Comment by domfarolino** [comment]
Well I'm not sure... there were changes requested. I honestly think most of this PR probably exists in the codebase one way or another since we have a decent cross-platform build flag system. Maybe someone could rebase this and see if there is anything remaining

**Comment by musgravejw** [comment]
Github closed this PR automatically when I tried to rebase, and for some reason won't let me re-open the PR, even though the branch is rolled back.  ¯\_(ツ)_/¯

**Comment by domfarolino** [comment]
It is saying there are 0 commits in this branch. So I think everything from this PR must be in the tree now, which means the overall PR is probably obsolete and empty.

**Pull request closed without merging**
