### PR TITLE
[WIP] Implement task_loop_for_io_linux

### PR DESCRIPTION
**Pull request by pmusgrave**

### CODE REVIEW

**Comment by domfarolino** [comment]
Is this a copy of the macos kqueue-based impl? My understanding is that kqueue isn’t implemented on Linux and that we’d have to manually use epoll.

Btw if you do want to test an implementation of task loop for IO you’ll have to modify https://github.com/domfarolino/browser/blob/master/base/scheduling/task_loop_for_io.h#L42 and change the macro in the TaskLoopForIO tests.

**Comment by pmusgrave** [comment]
Yep, switching to epoll, just using this as a starting point.

**Comment by musgravejw** [comment]
@domfarolino @pmusgrave Any suggestions for a replacement for `mach_msg_type_t`?  I didn't know if this was covered in the platform specific implementation or not, ie, whether we needed to replace it with a message passing system that worked on Debain.  Seems to be mainly used for `MachWakeup()`.

https://www.gnu.org/software/hurd/gnumach-doc/Message-Format.html

**Comment by pmusgrave** [comment]
I think if it's just being used to wake up a task loop, epoll has it's own wakeup mechanism and this isn't necessary

**Comment by domfarolino** [comment]
Could you elaborate on https://github.com/domfarolino/browser/pull/53#issuecomment-939368242?

eventfd sounds like the right direction but I’m on mobile right now so I want to be sure. The idea is that the task loop will become awake in one of two ways: either from a socket becoming ready to be read from, or a manual wakeup (MachWakeup on Mac) when a task is posted from another thread.

**Comment by pmusgrave** [comment]
The epoll version only has a list of file descriptors that it monitors, so eventfd is just a file descriptor that you can register to manually trigger events.

**Comment by domfarolino** [comment]
Ok then it sounds like we can use eventfd similar to how we are currently using mach_port_allocate in the mac version ctor.

**Comment by domfarolino** [comment]
Hey @pmusgrave, I've decided to pick this up over in #60 if that's alright, since it is currently blocking the mage IPC implementation and I've got some time to work on it. That PR is getting close to ready for review, and when it is I'll request your review on it.

Once it is merged, I'll [add you as a co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github) to it so that the credit is shared, since that PR is based off of yours here.

**Pull request closed without merging**
